name: CI/CD for EMS (Docker Only)

on:
  push:
    branches:
      - main

jobs:
  build-test-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SonarQube Code Analysis
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=AmbitiousLad_EmployeeManagementSystem-EMS-
          -Dsonar.organization=ambitiouslad
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t sanket245/ems:${{ github.sha }} -f employee_mgmt/Dockerfile .


    - name: Trivy security scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: sanket245/ems:${{ github.sha }}

    - name: Push Docker image
      run: docker push sanket245/ems:${{ github.sha }}

    - name: Run Docker container
      run: |
        docker run -d \
        --name ems-container \
        -p 8080:8080 \
        sanket245/ems:${{ github.sha }}
